dict_rename={'ANNOSCOLASTICO': 'anno',
           'AREAGEOGRAFICA': 'area',
           'CODICEISTITUTORIFERIMENTO': 'codice_istituto',
           'DENOMINAZIONEISTITUTORIFERIMENTO': 'denominazione_istituto',
           'CODICESCUOLA': 'codice_scuola',
    	   'DENOMINAZIONESCUOLA': 'denominazione_scuola',
           'INDIRIZZOSCUOLA': 'indirizzo',
           'CAPSCUOLA': 'cap',
           'CODICECOMUNESCUOLA': 'codice_comune',
           'DESCRIZIONECOMUNE': 'descrizione_comune',
           'DESCRIZIONECARATTERISTICASCUOLA': 'caratteristica_scuola',
           'DESCRIZIONETIPOLOGIAGRADOISTRUZIONESCUOLA': 'grado',
           'INDICAZIONESEDEDIRETTIVO': 'sede_direttivo',
           'INDICAZIONESEDEOMNICOMPRENSIVO': 'dominio_comprensivo',
           'INDIRIZZOEMAILSCUOLA': 'email',
           'INDIRIZZOPECSCUOLA': 'pec',
           'SITOWEBSCUOLA': 'website',
           'SEDESCOLASTICA': 'sede_scolastica':
           'ANNOCORSOCLASSE': 'ANNOCORSO'}

seismicity = {'Non classificato a rischio': 0,
'Rischio sismicitÃ\xa0 medio/alta (S=9)': 9,
'Rischio elevata sismicitÃ\xa0 (S=12)': 12,
'Rischio bassa sismicitÃ\xa0 (S=6)': 6,
'Non Comunicato': '-'}
